{ pkgs, ... }:

{
  hm = {
    programs = {
      firefox = {
        enable = true;
        package = pkgs.firefox-devedition;
        profiles.dev-edition-default = {
          isDefault = true;
          search = {
            force = true;
            default = "Kagi";
            privateDefault = "Kagi";
            engines = {
              "Kagi" = {
                urls = [{
                  template = "https://kagi.com/search?q={searchTerms}";
                }];
                icon = "https://help.kagi.com/favicon-16x16.png";
                updateInterval = 24 * 60 * 60 * 1000; # every day
                definedAliases = [ "@kg" ];
              };
              "Startpage" = {
                urls = [{
                  template = "https://www.startpage.com/sp/search?q=%s";
                }];
                iconUpdateUrl = "https://www.startpage.com/sp/cdn/favicons/favicon--default.ico";
                updateInterval = 24 * 60 * 60 * 1000; # every day
                definedAliases = [ "@sp" ];
              };
              "Nix Packages" = {
                urls = [{
                  template = "https://search.nixos.org/packages";
                  params = [
                    { name = "type"; value = "packages"; }
                    { name = "query"; value = "{searchTerms}"; }
                  ];
                }];

                icon = "${pkgs.nixos-icons}/share/icons/hicolor/scalable/apps/nix-snowflake.svg";
                definedAliases = [ "@np" ];
              };
              "NixOS Wiki" = {
                urls = [{ template = "https://wiki.nixos.org/index.php?search={searchTerms}"; }];
                icon = "https://wiki.nixos.org/favicon.ico";
                updateInterval = 24 * 60 * 60 * 1000; # every day
                definedAliases = [ "@nw" ];
              };
              "bing".metaData.hidden = true;
              "google".metaData.hidden = true;
              "Amazon".metaData.hidden = true;
            };
            order = [
              "ddg"
              "Startpage"
              "Nix Packages"
              "NixOS Wiki"
            ];
          };
          settings = {
            "services.sync.prefs.dangerously_allow_arbitrary" = true;
            "signon.rememberSignons" = false;
            "toolkit.legacyUserProfileCustomizations.stylesheets" = true;
            # Privacy settings generated by ffprofile.com
            "app.normandy.api_url" = "";
            "app.normandy.enabled" = false;
            "app.shield.optoutstudies.enabled" = false;
            "beacon.enabled" = false;
            "breakpad.reportURL" = "";
            "browser.aboutConfig.showWarning" = false;
            "browser.cache.offline.enable" = false;
            "browser.crashReports.unsubmittedCheck.autoSubmit" = false;
            "browser.crashReports.unsubmittedCheck.autoSubmit2" = false;
            "browser.crashReports.unsubmittedCheck.enabled" = false;
            "browser.disableResetPrompt" = true;
            "browser.fixup.alternate.enabled" = false;
            "browser.newtab.preload" = false;
            "browser.newtabpage.activity-stream.section.highlights.includePocket" = false;
            "browser.newtabpage.enhanced" = false;
            "browser.newtabpage.introShown" = true;
            "browser.safebrowsing.appRepURL" = "";
            "browser.safebrowsing.blockedURIs.enabled" = false;
            "browser.safebrowsing.downloads.enabled" = false;
            "browser.safebrowsing.downloads.remote.enabled" = false;
            "browser.safebrowsing.downloads.remote.url" = "";
            "browser.safebrowsing.enabled" = false;
            "browser.safebrowsing.malware.enabled" = false;
            "browser.safebrowsing.phishing.enabled" = false;
            "browser.selfsupport.url" = "";
            "browser.send_pings" = false;
            "browser.sessionstore.privacy_level" = 0;
            "browser.shell.checkDefaultBrowser" = false;
            "browser.startup.homepage_override.mstone" = "ignore";
            "browser.tabs.crashReporting.sendReport" = false;
            "browser.urlbar.groupLabels.enabled" = false;
            "browser.urlbar.quicksuggest.enabled" = false;
            "browser.urlbar.speculativeConnect.enabled" = false;
            "browser.urlbar.trimURLs" = false;
            "datareporting.healthreport.service.enabled" = false;
            "datareporting.healthreport.uploadEnabled" = false;
            "datareporting.policy.dataSubmissionEnabled" = false;
            "device.sensors.ambientLight.enabled" = false;
            "device.sensors.enabled" = false;
            "device.sensors.motion.enabled" = false;
            "device.sensors.orientation.enabled" = false;
            "device.sensors.proximity.enabled" = false;
            "dom.battery.enabled" = false;
            "dom.security.https_only_mode" = true;
            "dom.security.https_only_mode_ever_enabled" = true;
            "dom.webaudio.enabled" = false;
            "dom.private-attribution.submission.enabled" = false;
            "experiments.activeExperiment" = false;
            "experiments.enabled" = false;
            "experiments.manifest.uri" = false;
            "experiments.supported" = false;
            "extensions.getAddons.cache.enabled" = false;
            "extensions.getAddons.showPane" = false;
            "extensions.greasemonkey.stats.optedin" = false;
            "extensions.greasemonkey.stats.url" = "";
            "extensions.pocket.enabled" = false;
            "extensions.shield-recipe-client.api_url" = "";
            "extensions.shield-recipe-client.enabled" = false;
            "extensions.webservice.discoverURL" = "";
            "media.autoplay.default" = 0;
            "media.autoplay.enabled" = true;
            "media.navigator.enabled" = false;
            "media.video_stats.enabled" = false;
            "network.allow-experiments" = false;
            "network.cookie.cookieBehavior" = 1;
            "network.dns.disablePrefetch" = true;
            "network.dns.disablePrefetchFromHTTPS" = true;
            "network.http.referer.spoofSource" = true;
            "network.http.speculative-parallel-limit" = 0;
            "network.predictor.enable-prefetch" = false;
            "network.predictor.enabled" = false;
            "network.prefetch-next" = false;
            "network.trr.mode" = 5;
            "privacy.donottrackheader.enabled" = true;
            "privacy.donottrackheader.value" = 1;
            "privacy.query_stripping" = true;
            "privacy.trackingprotection.cryptomining.enabled" = true;
            "privacy.trackingprotection.enabled" = true;
            "privacy.trackingprotection.fingerprinting.enabled" = true;
            "privacy.trackingprotection.pbmode.enabled" = true;
            "privacy.usercontext.about_newtab_segregation.enabled" = true;
            "security.ssl.disable_session_identifiers" = true;
            "services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSite" = false;
            "signon.autofillForms" = false;
            "toolkit.telemetry.archive.enabled" = false;
            "toolkit.telemetry.bhrPing.enabled" = false;
            "toolkit.telemetry.cachedClientID" = "";
            "toolkit.telemetry.enabled" = false;
            "toolkit.telemetry.firstShutdownPing.enabled" = false;
            "toolkit.telemetry.hybridContent.enabled" = false;
            "toolkit.telemetry.newProfilePing.enabled" = false;
            "toolkit.telemetry.prompted" = 2;
            "toolkit.telemetry.rejected" = true;
            "toolkit.telemetry.reportingpolicy.firstRun" = false;
            "toolkit.telemetry.server" = "";
            "toolkit.telemetry.shutdownPingSender.enabled" = false;
            "toolkit.telemetry.unified" = false;
            "toolkit.telemetry.unifiedIsOptIn" = false;
            "toolkit.telemetry.updatePing.enabled" = false;
            # Browser UI customization
            "browser.download.autohideButton" = false;
            "browser.toolbars.bookmarks.visibility" = "always";
            "browser.newtabpage.activity-stream.showSponsoredTopSites" = false;
            "browser.newtabpage.activity-stream.topSitesRows" = 2;
            "browser.sessionstore.resume_session_once" = true;
            "general.autoScroll" = false;
            "browser.translations.automaticallyPopup" = false;
            # Vertical tabs
            "siderbar.revamp" = true;
            "sidebar.verticalTabs" = true;
            # Tab grouping
            "browser.tabs.groups.enabled" = true;
          };
        };
      };
      chromium = {
        enable = true;
        package = pkgs.brave;
      };
    };

    home.packages = with pkgs; [
      nur.repos.ymstnt.surf
    ];

    xdg.desktopEntries.firefox-developer-edition = {
      name = "Firefox Developer Edition";
      genericName = "Web Browser";
      exec = "firefox-developer-edition --name firefox-developer-edition %U";
      terminal = false;
      icon = "firefox-developer-edition";
      categories = [ "Network" "WebBrowser" ];
      actions = {
        "new-private-window" = {
          exec = "firefox-developer-edition --private-window %U";
          name = "New Private Window";
        };
        "new-window" = {
          exec = "firefox-developer-edition --new-window %U";
          name = "New Window";
        };
        "profile-manager-window" = {
          exec = "firefox-developer-edition --ProfileManager";
          name = "Profile Manager";
        };
      };
      mimeType = [ "text/html" "text/xml" "application/xhtml+xml" "application/vnd.mozilla.xul+xml" "x-scheme-handler/http" "x-scheme-handler/https" ];
      startupNotify = true;
      type = "Application";
      settings = {
        StartupWMClass = "Navigator";
      };
    };
  };
}
