format = """
[](#003F5E)\
$os\
$username\
[](bg:#005077 fg:#003F5E)\
$directory\
[](bg:#006496 fg:#005077)\
$git_branch\
$git_status\
[ ](fg:#006496)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#003F5E"
style_root = "bg:#003F5E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
format = '[󰣛 ]($style)'
style = "bg:#003F5E"
disabled = false # Disabled by default

[directory]
style = "bg:#005077"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰉋 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#006496"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#006496"
format = '[$all_status$ahead_behind ]($style)'
