#! /bin/sh

bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

# Fix resizing
bspc config pointer_motion_interval 50

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefoxdeveloperedition desktop='^1'
bspc rule -a discord desktop'^2' state=floating

# Change cursor to not look weird
xsetroot -cursor_name left_ptr &

nitrogen --set-auto $HOME/Pictures/Wallpapers/4e4sk39rdbt91.jpg --head=0 && nitrogen --set-auto $HOME/Pictures/Wallpapers/Dynamic/bell-dark.png --head=1

$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &
